/*
-- Query: select * from country
LIMIT 0, 50000

-- Date: 2024-03-05 15:53
*/
INSERT INTO `` (`country_code`,`country`) VALUES ('AD','Andorra');
INSERT INTO `` (`country_code`,`country`) VALUES ('AE','United Arab Emirates');
INSERT INTO `` (`country_code`,`country`) VALUES ('AF','Afghanistan');
INSERT INTO `` (`country_code`,`country`) VALUES ('AG','Antigua and Barbuda');
INSERT INTO `` (`country_code`,`country`) VALUES ('AI','Anguilla');
INSERT INTO `` (`country_code`,`country`) VALUES ('AL','Albania');
INSERT INTO `` (`country_code`,`country`) VALUES ('AM','Armenia');
INSERT INTO `` (`country_code`,`country`) VALUES ('AO','Angola');
INSERT INTO `` (`country_code`,`country`) VALUES ('AQ','Antarctica');
INSERT INTO `` (`country_code`,`country`) VALUES ('AR','Argentina');
INSERT INTO `` (`country_code`,`country`) VALUES ('AS','American Samoa');
INSERT INTO `` (`country_code`,`country`) VALUES ('AT','Austria');
INSERT INTO `` (`country_code`,`country`) VALUES ('AU','Australia');
INSERT INTO `` (`country_code`,`country`) VALUES ('AW','Aruba');
INSERT INTO `` (`country_code`,`country`) VALUES ('AX','Aland Islands');
INSERT INTO `` (`country_code`,`country`) VALUES ('AZ','Azerbaijan');
INSERT INTO `` (`country_code`,`country`) VALUES ('BA','Bosnia and Herzegovina');
INSERT INTO `` (`country_code`,`country`) VALUES ('BB','Barbados');
INSERT INTO `` (`country_code`,`country`) VALUES ('BD','Bangladesh');
INSERT INTO `` (`country_code`,`country`) VALUES ('BE','Belgium');
INSERT INTO `` (`country_code`,`country`) VALUES ('BF','Burkina Faso');
INSERT INTO `` (`country_code`,`country`) VALUES ('BG','Bulgaria');
INSERT INTO `` (`country_code`,`country`) VALUES ('BH','Bahrain');
INSERT INTO `` (`country_code`,`country`) VALUES ('BI','Burundi');
INSERT INTO `` (`country_code`,`country`) VALUES ('BJ','Benin');
INSERT INTO `` (`country_code`,`country`) VALUES ('BL','Saint Bartholemy');
INSERT INTO `` (`country_code`,`country`) VALUES ('BM','Bermuda');
INSERT INTO `` (`country_code`,`country`) VALUES ('BN','Brunei Darussalam');
INSERT INTO `` (`country_code`,`country`) VALUES ('BO','Bolivia, Plurinational State of');
INSERT INTO `` (`country_code`,`country`) VALUES ('BQ','Bonaire, Sint Eustatius and Saba');
INSERT INTO `` (`country_code`,`country`) VALUES ('BR','Brazil');
INSERT INTO `` (`country_code`,`country`) VALUES ('BS','Bahamas');
INSERT INTO `` (`country_code`,`country`) VALUES ('BT','Bhutan');
INSERT INTO `` (`country_code`,`country`) VALUES ('BV','Bouvet Island');
INSERT INTO `` (`country_code`,`country`) VALUES ('BW','Botswana');
INSERT INTO `` (`country_code`,`country`) VALUES ('BY','Belarus');
INSERT INTO `` (`country_code`,`country`) VALUES ('BZ','Belize');
INSERT INTO `` (`country_code`,`country`) VALUES ('CA','Canada');
INSERT INTO `` (`country_code`,`country`) VALUES ('CC','Cocos (Keeling) Islands');
INSERT INTO `` (`country_code`,`country`) VALUES ('CD','Congo, the Democratic Republic of the');
INSERT INTO `` (`country_code`,`country`) VALUES ('CF','Central African Republic');
INSERT INTO `` (`country_code`,`country`) VALUES ('CG','Congo');
INSERT INTO `` (`country_code`,`country`) VALUES ('CH','Switzerland');
INSERT INTO `` (`country_code`,`country`) VALUES ('CI','Cote d\'Ivoire');
INSERT INTO `` (`country_code`,`country`) VALUES ('CK','Cook Islands');
INSERT INTO `` (`country_code`,`country`) VALUES ('CL','Chile');
INSERT INTO `` (`country_code`,`country`) VALUES ('CM','Cameroon');
INSERT INTO `` (`country_code`,`country`) VALUES ('CN','China');
INSERT INTO `` (`country_code`,`country`) VALUES ('CO','Colombia');
INSERT INTO `` (`country_code`,`country`) VALUES ('CR','Costa Rica');
INSERT INTO `` (`country_code`,`country`) VALUES ('CU','Cuba');
INSERT INTO `` (`country_code`,`country`) VALUES ('CV','Cape Verde');
INSERT INTO `` (`country_code`,`country`) VALUES ('CW','Curacao');
INSERT INTO `` (`country_code`,`country`) VALUES ('CX','Christmas Island');
INSERT INTO `` (`country_code`,`country`) VALUES ('CY','Cyprus');
INSERT INTO `` (`country_code`,`country`) VALUES ('CZ','Czech Republic');
INSERT INTO `` (`country_code`,`country`) VALUES ('DE','Germany');
INSERT INTO `` (`country_code`,`country`) VALUES ('DJ','Djibouti');
INSERT INTO `` (`country_code`,`country`) VALUES ('DK','Denmark');
INSERT INTO `` (`country_code`,`country`) VALUES ('DM','Dominica');
INSERT INTO `` (`country_code`,`country`) VALUES ('DO','Dominican Republic');
INSERT INTO `` (`country_code`,`country`) VALUES ('DZ','Algeria');
INSERT INTO `` (`country_code`,`country`) VALUES ('EC','Ecuador');
INSERT INTO `` (`country_code`,`country`) VALUES ('EE','Estonia');
INSERT INTO `` (`country_code`,`country`) VALUES ('EG','Egypt');
INSERT INTO `` (`country_code`,`country`) VALUES ('EH','Western Sahara');
INSERT INTO `` (`country_code`,`country`) VALUES ('ER','Eritrea');
INSERT INTO `` (`country_code`,`country`) VALUES ('ES','Spain');
INSERT INTO `` (`country_code`,`country`) VALUES ('ET','Ethiopia');
INSERT INTO `` (`country_code`,`country`) VALUES ('FI','Finland');
INSERT INTO `` (`country_code`,`country`) VALUES ('FJ','Fiji');
INSERT INTO `` (`country_code`,`country`) VALUES ('FK','Falkland Islands (Malvinas)');
INSERT INTO `` (`country_code`,`country`) VALUES ('FM','Micronesia, Federated States of');
INSERT INTO `` (`country_code`,`country`) VALUES ('FO','Faroe Islands');
INSERT INTO `` (`country_code`,`country`) VALUES ('FR','France');
INSERT INTO `` (`country_code`,`country`) VALUES ('GA','Gabon');
INSERT INTO `` (`country_code`,`country`) VALUES ('GB','United Kingdom');
INSERT INTO `` (`country_code`,`country`) VALUES ('GD','Grenada');
INSERT INTO `` (`country_code`,`country`) VALUES ('GE','Georgia');
INSERT INTO `` (`country_code`,`country`) VALUES ('GF','French Guiana');
INSERT INTO `` (`country_code`,`country`) VALUES ('GG','Guernsey');
INSERT INTO `` (`country_code`,`country`) VALUES ('GH','Ghana');
INSERT INTO `` (`country_code`,`country`) VALUES ('GI','Gibraltar');
INSERT INTO `` (`country_code`,`country`) VALUES ('GL','Greenland');
INSERT INTO `` (`country_code`,`country`) VALUES ('GM','Gambia');
INSERT INTO `` (`country_code`,`country`) VALUES ('GN','Guinea');
INSERT INTO `` (`country_code`,`country`) VALUES ('GP','Guadeloupe');
INSERT INTO `` (`country_code`,`country`) VALUES ('GQ','Equatorial Guinea');
INSERT INTO `` (`country_code`,`country`) VALUES ('GR','Greece');
INSERT INTO `` (`country_code`,`country`) VALUES ('GS','South Georgia and the South Sandwich Islands');
INSERT INTO `` (`country_code`,`country`) VALUES ('GT','Guatemala');
INSERT INTO `` (`country_code`,`country`) VALUES ('GU','Guam');
INSERT INTO `` (`country_code`,`country`) VALUES ('GW','Guinea-Bissau');
INSERT INTO `` (`country_code`,`country`) VALUES ('GY','Guyana');
INSERT INTO `` (`country_code`,`country`) VALUES ('HK','Hong Kong');
INSERT INTO `` (`country_code`,`country`) VALUES ('HM','Heard Island and McDonald Islands');
INSERT INTO `` (`country_code`,`country`) VALUES ('HN','Honduras');
INSERT INTO `` (`country_code`,`country`) VALUES ('HR','Croatia');
INSERT INTO `` (`country_code`,`country`) VALUES ('HT','Haiti');
INSERT INTO `` (`country_code`,`country`) VALUES ('HU','Hungary');
INSERT INTO `` (`country_code`,`country`) VALUES ('ID','Indonesia');
INSERT INTO `` (`country_code`,`country`) VALUES ('IE','Ireland');
INSERT INTO `` (`country_code`,`country`) VALUES ('IL','Israel');
INSERT INTO `` (`country_code`,`country`) VALUES ('IM','Isle of Man');
INSERT INTO `` (`country_code`,`country`) VALUES ('IN','India');
INSERT INTO `` (`country_code`,`country`) VALUES ('IO','British Indian Ocean Territory');
INSERT INTO `` (`country_code`,`country`) VALUES ('IQ','Iraq');
INSERT INTO `` (`country_code`,`country`) VALUES ('IR','Iran, Islamic Republic of');
INSERT INTO `` (`country_code`,`country`) VALUES ('IS','Iceland');
INSERT INTO `` (`country_code`,`country`) VALUES ('IT','Italy');
INSERT INTO `` (`country_code`,`country`) VALUES ('JE','Jersey');
INSERT INTO `` (`country_code`,`country`) VALUES ('JM','Jamaica');
INSERT INTO `` (`country_code`,`country`) VALUES ('JO','Jordan');
INSERT INTO `` (`country_code`,`country`) VALUES ('JP','Japan');
INSERT INTO `` (`country_code`,`country`) VALUES ('KE','Kenya');
INSERT INTO `` (`country_code`,`country`) VALUES ('KG','Kyrgyzstan');
INSERT INTO `` (`country_code`,`country`) VALUES ('KH','Cambodia');
INSERT INTO `` (`country_code`,`country`) VALUES ('KI','Kiribati');
INSERT INTO `` (`country_code`,`country`) VALUES ('KM','Comoros');
INSERT INTO `` (`country_code`,`country`) VALUES ('KN','Saint Kitts and Nevis');
INSERT INTO `` (`country_code`,`country`) VALUES ('KP','Korea, Democratic People\'s Republic of');
INSERT INTO `` (`country_code`,`country`) VALUES ('KR','Korea, Republic of');
INSERT INTO `` (`country_code`,`country`) VALUES ('KW','Kuwait');
INSERT INTO `` (`country_code`,`country`) VALUES ('KY','Cayman Islands');
INSERT INTO `` (`country_code`,`country`) VALUES ('KZ','Kazakhstan');
INSERT INTO `` (`country_code`,`country`) VALUES ('LA','Lao People\'s Democratic Republic');
INSERT INTO `` (`country_code`,`country`) VALUES ('LB','Lebanon');
INSERT INTO `` (`country_code`,`country`) VALUES ('LC','Saint Lucia');
INSERT INTO `` (`country_code`,`country`) VALUES ('LI','Liechtenstein');
INSERT INTO `` (`country_code`,`country`) VALUES ('LK','Sri Lanka');
INSERT INTO `` (`country_code`,`country`) VALUES ('LR','Liberia');
INSERT INTO `` (`country_code`,`country`) VALUES ('LS','Lesotho');
INSERT INTO `` (`country_code`,`country`) VALUES ('LT','Lithuania');
INSERT INTO `` (`country_code`,`country`) VALUES ('LU','Luxembourg');
INSERT INTO `` (`country_code`,`country`) VALUES ('LV','Latvia');
INSERT INTO `` (`country_code`,`country`) VALUES ('LY','Libya');
INSERT INTO `` (`country_code`,`country`) VALUES ('MA','Morocco');
INSERT INTO `` (`country_code`,`country`) VALUES ('MC','Monaco');
INSERT INTO `` (`country_code`,`country`) VALUES ('MD','Moldova, Republic of');
INSERT INTO `` (`country_code`,`country`) VALUES ('ME','Montenegro');
INSERT INTO `` (`country_code`,`country`) VALUES ('MF','Saint Martin (French part)');
INSERT INTO `` (`country_code`,`country`) VALUES ('MG','Madagascar');
INSERT INTO `` (`country_code`,`country`) VALUES ('MH','Marshall Islands');
INSERT INTO `` (`country_code`,`country`) VALUES ('MK','Macedonia, the Former Yugoslav Republic of');
INSERT INTO `` (`country_code`,`country`) VALUES ('ML','Mali');
INSERT INTO `` (`country_code`,`country`) VALUES ('MM','Myanmar');
INSERT INTO `` (`country_code`,`country`) VALUES ('MN','Mongolia');
INSERT INTO `` (`country_code`,`country`) VALUES ('MO','Macao');
INSERT INTO `` (`country_code`,`country`) VALUES ('MP','Northern Mariana Islands');
INSERT INTO `` (`country_code`,`country`) VALUES ('MQ','Martinique');
INSERT INTO `` (`country_code`,`country`) VALUES ('MR','Mauritania');
INSERT INTO `` (`country_code`,`country`) VALUES ('MS','Montserrat');
INSERT INTO `` (`country_code`,`country`) VALUES ('MT','Malta');
INSERT INTO `` (`country_code`,`country`) VALUES ('MU','Mauritius');
INSERT INTO `` (`country_code`,`country`) VALUES ('MV','Maldives');
INSERT INTO `` (`country_code`,`country`) VALUES ('MW','Malawi');
INSERT INTO `` (`country_code`,`country`) VALUES ('MX','Mexico');
INSERT INTO `` (`country_code`,`country`) VALUES ('MY','Malaysia');
INSERT INTO `` (`country_code`,`country`) VALUES ('MZ','Mozambique');
INSERT INTO `` (`country_code`,`country`) VALUES ('NA','Namibia');
INSERT INTO `` (`country_code`,`country`) VALUES ('NC','New Caledonia');
INSERT INTO `` (`country_code`,`country`) VALUES ('NE','Niger');
INSERT INTO `` (`country_code`,`country`) VALUES ('NF','Norfolk Island');
INSERT INTO `` (`country_code`,`country`) VALUES ('NG','Nigeria');
INSERT INTO `` (`country_code`,`country`) VALUES ('NI','Nicaragua');
INSERT INTO `` (`country_code`,`country`) VALUES ('NL','Netherlands');
INSERT INTO `` (`country_code`,`country`) VALUES ('NO','Norway');
INSERT INTO `` (`country_code`,`country`) VALUES ('NP','Nepal');
INSERT INTO `` (`country_code`,`country`) VALUES ('NR','Nauru');
INSERT INTO `` (`country_code`,`country`) VALUES ('NU','Niue');
INSERT INTO `` (`country_code`,`country`) VALUES ('NZ','New Zealand');
INSERT INTO `` (`country_code`,`country`) VALUES ('OM','Oman');
INSERT INTO `` (`country_code`,`country`) VALUES ('PA','Panama');
INSERT INTO `` (`country_code`,`country`) VALUES ('PE','Peru');
INSERT INTO `` (`country_code`,`country`) VALUES ('PF','French Polynesia');
INSERT INTO `` (`country_code`,`country`) VALUES ('PG','Papua New Guinea');
INSERT INTO `` (`country_code`,`country`) VALUES ('PH','Philippines');
INSERT INTO `` (`country_code`,`country`) VALUES ('PK','Pakistan');
INSERT INTO `` (`country_code`,`country`) VALUES ('PL','Poland');
INSERT INTO `` (`country_code`,`country`) VALUES ('PM','Saint Pierre and Miquelon');
INSERT INTO `` (`country_code`,`country`) VALUES ('PN','Pitcairn');
INSERT INTO `` (`country_code`,`country`) VALUES ('PR','Puerto Rico');
INSERT INTO `` (`country_code`,`country`) VALUES ('PS','Palestine, State of');
INSERT INTO `` (`country_code`,`country`) VALUES ('PT','Portugal');
INSERT INTO `` (`country_code`,`country`) VALUES ('PW','Palau');
INSERT INTO `` (`country_code`,`country`) VALUES ('PY','Paraguay');
INSERT INTO `` (`country_code`,`country`) VALUES ('QA','Qatar');
INSERT INTO `` (`country_code`,`country`) VALUES ('RE','Reunion');
INSERT INTO `` (`country_code`,`country`) VALUES ('RO','Romania');
INSERT INTO `` (`country_code`,`country`) VALUES ('RS','Serbia');
INSERT INTO `` (`country_code`,`country`) VALUES ('RU','Russian Federation');
INSERT INTO `` (`country_code`,`country`) VALUES ('RW','Rwanda');
INSERT INTO `` (`country_code`,`country`) VALUES ('SA','Saudi Arabia');
INSERT INTO `` (`country_code`,`country`) VALUES ('SB','Solomon Islands');
INSERT INTO `` (`country_code`,`country`) VALUES ('SC','Seychelles');
INSERT INTO `` (`country_code`,`country`) VALUES ('SD','Sudan');
INSERT INTO `` (`country_code`,`country`) VALUES ('SE','Sweden');
INSERT INTO `` (`country_code`,`country`) VALUES ('SG','Singapore');
INSERT INTO `` (`country_code`,`country`) VALUES ('SH','Saint Helena, Ascension and Tristan da Cunha');
INSERT INTO `` (`country_code`,`country`) VALUES ('SI','Slovenia');
INSERT INTO `` (`country_code`,`country`) VALUES ('SJ','Svalbard and Jan Mayen');
INSERT INTO `` (`country_code`,`country`) VALUES ('SK','Slovakia');
INSERT INTO `` (`country_code`,`country`) VALUES ('SL','Sierra Leone');
INSERT INTO `` (`country_code`,`country`) VALUES ('SM','San Marino');
INSERT INTO `` (`country_code`,`country`) VALUES ('SN','Senegal');
INSERT INTO `` (`country_code`,`country`) VALUES ('SO','Somalia');
INSERT INTO `` (`country_code`,`country`) VALUES ('SR','Suriname');
INSERT INTO `` (`country_code`,`country`) VALUES ('SS','South Sudan');
INSERT INTO `` (`country_code`,`country`) VALUES ('ST','Sao Tome and Principe');
INSERT INTO `` (`country_code`,`country`) VALUES ('SV','El Salvador');
INSERT INTO `` (`country_code`,`country`) VALUES ('SX','Sint Maarten (Dutch part)');
INSERT INTO `` (`country_code`,`country`) VALUES ('SY','Syrian Arab Republic');
INSERT INTO `` (`country_code`,`country`) VALUES ('SZ','Swaziland');
INSERT INTO `` (`country_code`,`country`) VALUES ('TC','Turks and Caicos Islands');
INSERT INTO `` (`country_code`,`country`) VALUES ('TD','Chad');
INSERT INTO `` (`country_code`,`country`) VALUES ('TF','French Southern Territories');
INSERT INTO `` (`country_code`,`country`) VALUES ('TG','Togo');
INSERT INTO `` (`country_code`,`country`) VALUES ('TH','Thailand');
INSERT INTO `` (`country_code`,`country`) VALUES ('TJ','Tajikistan');
INSERT INTO `` (`country_code`,`country`) VALUES ('TK','Tokelau');
INSERT INTO `` (`country_code`,`country`) VALUES ('TL','Timor-Leste');
INSERT INTO `` (`country_code`,`country`) VALUES ('TM','Turkmenistan');
INSERT INTO `` (`country_code`,`country`) VALUES ('TN','Tunisia');
INSERT INTO `` (`country_code`,`country`) VALUES ('TO','Tonga');
INSERT INTO `` (`country_code`,`country`) VALUES ('TR','Turkey');
INSERT INTO `` (`country_code`,`country`) VALUES ('TT','Trinidad and Tobago');
INSERT INTO `` (`country_code`,`country`) VALUES ('TV','Tuvalu');
INSERT INTO `` (`country_code`,`country`) VALUES ('TW','Taiwan, Province of China');
INSERT INTO `` (`country_code`,`country`) VALUES ('TZ','Tanzania, United Republic of');
INSERT INTO `` (`country_code`,`country`) VALUES ('UA','Ukraine');
INSERT INTO `` (`country_code`,`country`) VALUES ('UG','Uganda');
INSERT INTO `` (`country_code`,`country`) VALUES ('UM','United States Minor Outlying Islands');
INSERT INTO `` (`country_code`,`country`) VALUES ('US','United States');
INSERT INTO `` (`country_code`,`country`) VALUES ('UY','Uruguay');
INSERT INTO `` (`country_code`,`country`) VALUES ('UZ','Uzbekistan');
INSERT INTO `` (`country_code`,`country`) VALUES ('VA','Holy See (Vatican City State)');
INSERT INTO `` (`country_code`,`country`) VALUES ('VC','Saint Vincent and the Grenadines');
INSERT INTO `` (`country_code`,`country`) VALUES ('VE','Venezuela, Bolivarian Republic of');
INSERT INTO `` (`country_code`,`country`) VALUES ('VG','Virgin Islands, British');
INSERT INTO `` (`country_code`,`country`) VALUES ('VI','Virgin Islands, U.S.');
INSERT INTO `` (`country_code`,`country`) VALUES ('VN','Viet Nam');
INSERT INTO `` (`country_code`,`country`) VALUES ('VU','Vanuatu');
INSERT INTO `` (`country_code`,`country`) VALUES ('WF','Wallis and Futuna');
INSERT INTO `` (`country_code`,`country`) VALUES ('WS','Samoa');
INSERT INTO `` (`country_code`,`country`) VALUES ('XK','Kosovo');
INSERT INTO `` (`country_code`,`country`) VALUES ('YE','Yemen');
INSERT INTO `` (`country_code`,`country`) VALUES ('YT','Mayotte');
INSERT INTO `` (`country_code`,`country`) VALUES ('ZA','South Africa');
INSERT INTO `` (`country_code`,`country`) VALUES ('ZM','Zambia');
INSERT INTO `` (`country_code`,`country`) VALUES ('ZW','Zimbabwe');
